version: "3"
services: 
    rabbitmq-container:
        image: rabbitmq:3-management
        ports: 
            - 5673:5672
            - 15672:15672

    mysql-container:
        image: mysql:5.7
        restart: always
        ports: 
            - 3306:3306
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=skt
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password